/*
 * 자동차
 * 
 * - 자동차 번호
 * - 자동차 브랜드
 * - 출시 날짜
 * - 색상
 * - 가격
 * 
 * */

CREATE TABLE TBL_CAR(
	CAR_ID NUMBER,
	CAR_BRAND VARCHAR2(1000),
	CAR_RELEASEDATE DATE,
	CAR_COLOR VARCHAR(1000),
	CAR_PRICE NUMBER,
	CONSTRAINT PK_CAR PRIMARY KEY(CAR_ID)
);

CREATE TABLE TBL_CAR(
	CAR_ID NUMBER CONSTRAINT PK_CAR PRIMARY KEY,
	CAR_BRAND VARCHAR2(1000),
	CAR_RELEASEDATE DATE,
	CAR_COLOR VARCHAR(1000),
	CAR_PRICE NUMBER
);

CREATE TABLE TBL_CAR(
	CAR_ID NUMBER PRIMARY KEY,
	CAR_BRAND VARCHAR(1000),
	CAR_RELEASEDATE DATE,
	CAR_COLOR VARCHAR(1000),
	CAR_PRICE NUMBER
);

DROP TABLE TBL_CAR;

ALTER TABLE TBL_CAR DROP CONSTRAINT PK_CAR;
ALTER TABLE TBL_CAR ADD CONSTRAINT PK_CAR PRIMARY KEY(CAR_ID);

/*
 * 동물 테이블 생성
 * 
 * - 고유 번호
 * - 종류
 * - 나이
 * - 먹이
 * 
 * */

CREATE TABLE TBL_ANIMAL2(
	ANIMAL2_ID NUMBER,
	ANIMAL2_TYPE VARCHAR2(1000),
	ANIMAL2_AGE NUMBER,
	ANIMAL2_FEED VARCHAR2(1000),
	CONSTRAINT PK_ANIMAL2 PRIMARY KEY(ANIMAL2_ID)
);

ALTER TABLE TBL_ANIMAL2 DROP CONSTRAINT PK_ANIMAL2;
ALTER TABLE TBL_ANIMAL2 ADD CONSTRAINT PK_ANIMAL2 PRIMARY KEY(ANIMAL2_ID);

DROP TABLE TBL_ANIMAL2;
/*
 * 학생 테이블 생성
 * 
 * - 학생 번호
 * - 학생 아이디
 * - 학생 이름
 * - 전공
 * - 성별
 * - 생년월일
 * - 학생 나이 NOT NULL, DEFAULT는 생년월일로 계산된 나이, 19보다 커야한다
 * - 학생 학점(A+ ~ F) 'A+', 'A', 'B+', 'B', 'C+', 'C', 'D+', 'D', 'F'
 * 
 */

CREATE TABLE TBL_STUDENT2(
	/*PRIMARY KEY : 고유한 값, 중복이 없고 NULL값을 허용하지 않는다.*/
	STUDENT2_ID NUMBER CONSTRAINT PK_STUDENT2 PRIMARY KEY,
	/*UNIQUE : NULL값은 허용하지만 중복은 허용하지 않는다.*/
	STUDENT2_IDENTIFICATION VARCHAR2(1000) CONSTRAINT UK_STUDENT2 UNIQUE,
	/*NOT NULL : NULL값 입력 불가*/
	STUDENT2_NAME VARCHAR2(1000) CONSTRAINT REQUIER_NAME NOT NULL,
	STUDENT2_MAJOR VARCHAR2(1000) CONSTRAINT REQUIER_MAJOR NOT NULL,
	STUDENT2_GENDER CHAR(1) DEFAULT 'N'CONSTRAINT BAN_GENDER,
	STUDENT2_BIRTH DATE CONSTRAINT BAN_BIRTH ,
);








